<a href="https://colab.research.google.com/github/feb24praveen/NumPy-Task-Exercises./blob/main/Numpy_task_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Task 2 Exercises**



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
version=(np.__version__)
print(version)


conf=np.show_config()
print(conf)

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
null_vector=np.zeros(10)              #      .astype(int) is used to convert float to integers.
print(null_vector)

null_vector=np.zeros(10).astype(int)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
memory_size=np.array((20,30))

print("%d bytes" % (memory_size.size * memory_size.itemsize))

16 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
Null= np.zeros(10).astype(int)
Null[4] = 1
print(Null)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
vector=np.arange(50)
reversed=vector[::-1]
print(reversed)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
mat=np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
non= np.nonzero([1,2,0,0,4,0])
print(non)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
random_values=np.random.random(27).reshape(3,3,3)
print(random_values)

[[[0.18377665 0.62801754 0.30305751]
  [0.47065114 0.2403002  0.45698797]
  [0.45738117 0.5775356  0.81110205]]

 [[0.12016131 0.686473   0.53875775]
  [0.25413356 0.15726462 0.90021213]
  [0.18800097 0.30977372 0.36642982]]

 [[0.03218627 0.30990559 0.10124404]
  [0.1487837  0.28328286 0.9346859 ]
  [0.80289443 0.67459793 0.80664453]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
Array=np.random.random((10,10))
Array_max=np.max(Array)
Array_min=np.min(Array)
print("Array_max is:",Array_max)
print("Array_max is:",Array_min)

Array_max is: 0.9961447916210062
Array_max is: 0.011409086657127587


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
Vector = np.random.random(30)
mean_value = np.mean(Vector)
print('Mean value of Random vector is:',mean_value)

Mean value of Random vector is: 0.5751821673585789


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
Array = np.ones((10,10))
Array[1:-1,1:-1] = 0
print(Array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
border = np.ones((3,3))
border = np.pad(border,constant_values=0,pad_width=1)
print(border)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
Diagonal_matrix= np.diag (1+np.arange(4), k=-1)
print(Diagonal_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

> Indented block


(**hint**: np.unravel_index)

In [ ]:
hund_ele=np.unravel_index(99,(6,7,8))
print(hund_ele)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
checkboard =np.tile(np.array([[0,1],[1,0]]),(4,4))
print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
df= np.random.random((5,5))
print("Original Array:",(df))

dfmax, dfmin = df.max(), df.min()
df = (df - dfmin)/(dfmax - dfmin)
print(df)
print('$'*70)
print("After normalization:")
print(df)

Original Array: [[0.21289509 0.62807774 0.1832447  0.85216609 0.33648281]
 [0.3055375  0.90462955 0.07889056 0.32387234 0.22532967]
 [0.61042727 0.53548777 0.87483114 0.16948723 0.98512242]
 [0.52184713 0.54898061 0.75378098 0.30269637 0.04374217]
 [0.8961779  0.03119583 0.28726567 0.75964856 0.28700841]]
[[0.1904751  0.62571052 0.15939264 0.86062205 0.32003194]
 [0.28759202 0.91561942 0.04999832 0.30681241 0.20351025]
 [0.60720757 0.52864858 0.88438179 0.14497069 1.        ]
 [0.51434912 0.54279311 0.75748506 0.28461366 0.01315231]
 [0.90675957 0.         0.26843768 0.76363604 0.26816799]]
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
After normalization:
[[0.1904751  0.62571052 0.15939264 0.86062205 0.32003194]
 [0.28759202 0.91561942 0.04999832 0.30681241 0.20351025]
 [0.60720757 0.52864858 0.88438179 0.14497069 1.        ]
 [0.51434912 0.54279311 0.75748506 0.28461366 0.01315231]
 [0.90675957 0.         0.26843768 0.76363604 0.26816799]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
Cust_col = np.dtype([('R',np.ubyte),
                  ('G',np.ubyte),
                  ('B',np.ubyte),
                  ('A',np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
matrix =np.dot(np.random.random((5,3)),np.random.random((3,2)))
print(matrix)

[[1.26939842 0.75035477]
 [1.51932216 1.05063863]
 [0.45529736 0.27995876]
 [0.87977957 0.56792873]
 [1.13207973 0.78000437]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
array=np.arange((11))

array[4:8]=np.multiply(array[4:8],-1)

print(array)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# legal_expressions = 1,2,3and 4

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-27-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-27-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
round_off= np.random.uniform(-10,+15,15)
print(np.copysign(np.ceil(np.abs(round_off)), round_off))

[  9. -10.   7.   2.  -7.  13.  -5.  -1.  -2.   3.   7.   6.  12.  -9.
   1.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
X = np.array([0,2,1,5,8,3,6]) 
Y = np.array([0,2,4,3]) 

print(np.intersect1d(X, Y))

[0 2 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
data = np.random.random(1000).reshape(10, 10,10) * np.nan
np.seterr(all="ignore")
np.nanmedian(data, axis=[1, 2])

/usr/local/lib/python3.10/dist-packages/numpy/lib/nanfunctions.py:1218: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

In [ ]:
exp=(np.sqrt(-1)==np.emath.sqrt(-1))
print(exp)

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
Yesterday = np.datetime64('today')-np.timedelta64(1)
Today = np.datetime64('today')
Tomorrow = np.datetime64('today') + np.timedelta64(1)
print(Yesterday)
print(Today)
print(Tomorrow)

2023-04-30
2023-05-01
2023-05-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
int_part = np.random.uniform(0,20,10)

print (int_part - int_part%1)
print (np.floor(int_part))
print (np.ceil(int_part)-1)
print (int_part.astype(int))
print (np.trunc(int_part))

[ 5. 16.  1.  6. 17.  2. 12. 13. 17.  2.]
[ 5. 16.  1.  6. 17.  2. 12. 13. 17.  2.]
[ 5. 16.  1.  6. 17.  2. 12. 13. 17.  2.]
[ 5 16  1  6 17  2 12 13 17  2]
[ 5. 16.  1.  6. 17.  2. 12. 13. 17.  2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
matrix = np.zeros((5,5))   
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
  for x in range(10):
     yield (x)
gen= np.fromiter(generate(),dtype=int,count=-1)
print(gen)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
vector=np.linspace(0,1,11,endpoint=False)[1:]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
vect=np.random.random(10)
vector=np.sort(vect)
print(vector)

[0.01077201 0.10583637 0.49909578 0.55917514 0.56023794 0.56226084
 0.64976888 0.76963222 0.8687242  0.88964317]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
array=np.arange(10)
small_array=np.add.reduce(array)
print(small_array)

45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A=np.random.random(10)
B=np.random.random(10)
One=np.array_equal(A,B)
print(One)
Two=np.allclose(A,B)
print(Two)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
array= np.zeros(10)
array.flags.writeable=False
#array[0]=1           ############ ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.21822444 1.30742979 1.35940993 0.6580082  0.86542228 1.14556343
 1.22787568 0.57233099 0.83594314 0.72311528]
[0.6840789  0.74956176 0.75725474 0.00149035 0.02922188 0.68028747
 0.95092426 0.25637129 1.14170843 0.94191329]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
random_vector = np.random.random(10)
random_vector[random_vector.argmax()] = 0
print(random_vector)

[0.         0.71242692 0.20017044 0.79288332 0.52459632 0.31532246
 0.24457978 0.44455165 0.02960658 0.63035166]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
area = np.zeros((5,5),[('x',float),('y',float)])
area['x'],area['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(area)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
values = np.ones((4,4))
np.set_printoptions(threshold=float(inf))
print(values)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
closest_value= np.arange(100)
vector = np.random.uniform(0,100)
index = (np.abs(closest_value-vector)).argmin()
print(closest_value[index])

43


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z = np.ones (10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


/usr/local/lib/python3.10/dist-packages/numpy/core/numeric.py:204: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
a= np.random.random((10,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.59026293 0.16092577 0.36767018 0.5756965  0.80902938
  0.30062795 0.76538727 0.63398223 0.88242949]
 [0.59026293 0.         0.69458818 0.8155528  0.24696666 0.49562994
  0.88946997 0.33901492 0.14910858 0.51480054]
 [0.16092577 0.69458818 0.         0.47040113 0.71856607 0.9635372
  0.26658663 0.90789446 0.70852252 1.03414781]
 [0.36767018 0.8155528  0.47040113 0.         0.68474777 0.81100017
  0.33140197 0.84785876 0.90819054 0.89863835]
 [0.5756965  0.24696666 0.71856607 0.68474777 0.         0.28068035
  0.84716502 0.18978817 0.39568147 0.32973037]
 [0.80902938 0.49562994 0.9635372  0.81100017 0.28068035 0.
  1.04523968 0.17814522 0.64018729 0.08879255]
 [0.30062795 0.88946997 0.26658663 0.33140197 0.84716502 1.04523968
  0.         1.03313578 0.93328332 1.12671735]
 [0.76538727 0.33901492 0.90789446 0.84785876 0.18978817 0.17814522
  1.03313578 0.         0.47579583 0.17641476]
 [0.63398223 0.14910858 0.70852252 0.90819054 0.39568147 0.64018729
  0.93328332 0.475795

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
Z = (np.random.rand(10)*10).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[8 5 1 4 8 5 0 8 6 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
array = np.arange(8).reshape(2,2,2)
for index, value in np.ndenumerate(array):
    print(index, value)
for index in np.ndindex(array.shape):
    print(index, array[index])

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7
(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
num= 10
p = 3
array= np.ones((num,num))
np.put(array, np.random.choice(range(num*num), p, replace=False),1)
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
array = np.random.rand (3,6)
mean_row = array - array.mean (axis=1,keepdims=True)
print(mean_row)


[[ 0.10801047  0.45108193 -0.36220168 -0.2977984   0.46716726 -0.36625958]
 [ 0.42589698 -0.0693241  -0.3038057  -0.14194465 -0.15791105  0.24708852]
 [-0.37607543 -0.16527776 -0.40642703  0.4162726   0.19323492  0.3382727 ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
array= np.random.randint(0,8,(2,8))
print(array)
print(array[array[:,1].argsort()])

[[0 7 1 1 1 3 3 5]
 [0 7 0 5 6 6 2 4]]
[[0 7 1 1 1 3 3 5]
 [0 7 0 5 6 6 2 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
nums = np.random.randint(0,5,(3,15))
print(nums)
print((~nums.any(axis=0)).any())

[[2 2 4 4 3 2 2 2 3 4 2 2 0 2 1]
 [4 1 2 4 0 2 3 1 3 3 4 2 0 4 1]
 [3 4 0 2 4 3 1 1 1 1 1 0 1 1 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
array= np.random.uniform(0,5,12)
number = 1
value = array.flat [np.abs(array - number).argmin()]
print(value)

0.9096853433829555


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name='attribute'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name','attribute')

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
array1= np.random.rand(10,10)
array2 = np.random.rand(10,10)

print(np.diag(np.dot(array1, array2)))
print(array1)

[2.56234959 4.13645415 2.98952585 1.9012818  1.83504945 2.79671753
 2.93380272 2.30461089 2.31213812 2.41282541]
[[0.80787669 0.18051122 0.85553793 0.90021807 0.96771317 0.2509146
  0.30232106 0.84326692 0.36492789 0.90154986]
 [0.55089982 0.88451077 0.47578345 0.25516029 0.35210789 0.26937734
  0.94993313 0.91521268 0.67575033 0.92791305]
 [0.23397437 0.69704588 0.17375246 0.58177569 0.95699796 0.64592699
  0.10441787 0.00165407 0.41114222 0.81248775]
 [0.57386058 0.97933182 0.29154267 0.28827379 0.1069282  0.62576776
  0.43105924 0.15345776 0.71680171 0.0850846 ]
 [0.32667843 0.62295143 0.14672688 0.99854795 0.16293202 0.6021607
  0.74678715 0.00534785 0.31257128 0.23838683]
 [0.23144591 0.13641549 0.22301502 0.8520221  0.89851834 0.61962267
  0.36960894 0.97247704 0.38372561 0.99727938]
 [0.56093628 0.13275168 0.48010141 0.06986557 0.76121315 0.85182435
  0.52799886 0.78493632 0.7003554  0.77300864]
 [0.71787712 0.49278776 0.75825009 0.87146773 0.78053637 0.00956759
  0.98799607 0.4

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
vector= np.array([1,2,3,4,5])
print(vector)
p = 3

new_vector = np.zeros(len(vector) + (len(vector)-1)*(p))
new_vector[::p+1] = vector
print(new_vector)

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
number1 = np.ones((5,5,3))
number2 = 3*np.ones((5,5))
print(number1)

new_array = number1 * number2[:,:,None]
print(new_array)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
array = np.array([[4,3, 1],[5 ,7, 0],[9, 9, 3],[8, 2, 4]]) 
print(array)
array[[0, 2]] = array[[2, 0]]
print(array)

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]
[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

### 74.Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)
print(len(C))

[1 1 2 3 4 4 6]
7


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=5) :
    test = np.cumsum(a, dtype=float)
    test[n:] = test[n:] - test[:-n]
    return test[n - 1:] / n

array = np.arange(11)
print(moving_average(array, n=5))

[2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
matrix = np.array([[1, 2, 3, 23],
                       [4, 5, 6, 25],
                       [7, 8, 9, 28],
                       [10, 11, 12, 41]])
print("Matrix rank is:",np.linalg.svd(matrix))

Matrix rank is: (array([[-0.34818254, -0.85229605,  0.08116512, -0.38180177],
       [-0.40689172, -0.22850109, -0.3733219 ,  0.80178373],
       [-0.47982228,  0.33767402, -0.66770825, -0.45816213],
       [-0.69496664,  0.32765067,  0.63891211,  0.03818018]]), array([6.50128811e+01, 6.48977632e+00, 4.56173231e-01, 1.21024377e-15]), array([[-1.88949814e-01, -2.18634134e-01, -2.48318454e-01,
        -9.24572890e-01],
       [ 5.96927261e-01,  5.32907728e-01,  4.68888195e-01,
        -3.73939913e-01],
       [ 6.64311031e-01, -3.92657880e-02, -7.42842607e-01,
         7.30336401e-02],
       [ 4.08248290e-01, -8.16496581e-01,  4.08248290e-01,
         2.22044605e-16]]))


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
x = np.random.randint(0, 10, 20)
print(x)
print(np.bincount(x).argmax())

[0 0 2 5 4 8 0 0 5 8 4 5 2 9 0 4 5 3 4 2]
0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
array = np.arange(20)
print(array)
np.random.shuffle(array)
n = 1
print (array[np.argsort(array)[-n:]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
vectors = np.array([0, 1, 2, 3, 15, 16, 32], dtype=np.uint8)
print(np.unpackbits(vectors[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)